code/__DEFINES/role_preferences.dm
code/game/objects/items/implants/implant_compliance.dm
code/modules/admin/sql_ban_system.dm
code/modules/antagonists/compliance_implant/compliance_implant.dm
code/modules/research/designs/medical_designs.dm
code/modules/research/techweb/all_nodes.dm
tgstation.dme

Adds the Compliance Implant as part of the Security Arsenal; A much-more limited use implant that, instead of implanting a trigger phrase into a subject to be used at whim ala the Enhanced Interrogation Chamber, injects them with a pre-configured phrase emploring them to assist a company and a specific department within it so long as the implant remains within them.
If the implant case is emagged, this goal changes towards helping a specific person instead. You *will* need to set the name to your own, or another's, or an alias, manually..
:cl:
add: Compliance Implants have been added, a dumbed-down, direct-application bit of customizable brainwashing to make sure prisoners stay in line. Consult the ethical review board for more information.
/:cl:

[BOUNTY] Compliance Implant

---

_maps/RandomRuins/IceRuins/icemoon_surface_engioutpost.dmm
_maps/RandomRuins/IceRuins/skyrat/icemoon_underground_syndicate_base1_skyrat.dmm
_maps/RandomRuins/LavaRuins/skyrat/lavaland_surface_syndicate_base1_skyrat.dmm
_maps/RandomRuins/SpaceRuins/TheDerelict.dmm
_maps/RandomRuins/SpaceRuins/forgottenship.dmm
_maps/RandomRuins/SpaceRuins/oldstation.dmm
_maps/RandomRuins/SpaceRuins/skyrat/cargodiselost.dmm
_maps/RandomRuins/SpaceRuins/skyrat/interdynefob.dmm
_maps/RandomRuins/SpaceRuins/skyrat/port_tarkon/defcon2.dmm
_maps/RandomRuins/SpaceRuins/skyrat/port_tarkon/defcon3.dmm
_maps/RandomRuins/SpaceRuins/skyrat/port_tarkon/defcon4.dmm
_maps/RandomRuins/SpaceRuins/skyrat/port_tarkon/defcon5.dmm
code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
code/game/objects/items/storage/boxes/science_boxes.dm
code/modules/research/machinery/_production.dm
code/modules/research/machinery/circuit_imprinter.dm
code/modules/research/machinery/departmental_protolathe.dm
code/modules/research/machinery/protolathe.dm
modular_skyrat/master_files/code/modules/research/machinery/departmental_circuit_imprinter.dm
tgstation.dme

https://www.youtube.com/watch?v=aHl0h6nHBNM
:cl:
balance: Lathes no longer tax silicons or people not of their assigned department - by default.
balance: Ghostroles have omnilathes again. Surely this can't go wrong.
/:cl:

Disables Lathe Tax, Reverts Offstation Lathes to Omnilathes

---

code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm

Ports /tg/station PR 70796.
:cl: GoldenAlpharex for /tg/station
fix: Being hit by the freezing breath of two (or more) ice whelps will no longer leave you looking like an ice cube for the rest of the round.
/:cl:

[PORT] Fixes the ice block status effect not clearing the ice block overlay upon being replaced

---

code/datums/wires/_wires.dm
code/game/objects/items/devices/multitool.dm
code/game/objects/items/storage/boxes/science_boxes.dm
code/game/objects/items/tools/crowbar.dm
code/game/objects/items/tools/screwdriver.dm
code/game/objects/items/tools/weldingtool.dm
code/modules/power/cell.dm
code/modules/research/stock_parts.dm
code/modules/research/stock_parts/stock_part_datum.dm
modular_skyrat/modules/icspawning/code/standard.dm
modular_skyrat/modules/multicellcharger/code/multi_cell_charger.dm

These need sprites too (I beleive someone else was already asked?) But codewise, they're complete. I've tested to make sure material count doesn't underflow personally, and everything SEEMS to be above board.
Also gives BSTS WB-32 tools, which are either rethemes or upgrades to abductor tools.
:cl:
add: Lore-Based, nigh unobtainable Stock Parts and tools have been added. Will YOU see them?
/:cl:

[LORE] WB-32 Tools + Stock Parts, Minus Sprites

---

code/game/machinery/doors/airlock.dm

Hey did you know that the admin jaws were IDENTICAL speed to normal jaws because of this goofy bit hijinx
this addresses that, making the admin-only jaws actually fast as fuck
also the syndicate ones I guess
:cl:
balance: The syndicate jaws of life now, genuinely, pries doors faster than the normal version.
/:cl:

[FUCK] Jaws prying is now affected by toolspeed

---

code/datums/id_trim/jobs.dm

:cl:
del: The chef no longer has morgue access. You know why.
/:cl:

1984s Soylent Green

---

code/__DEFINES/time.dm

yeah
:cl:
qol: It is now ACTUALLY 4023. Stop looking at your PDAs. Don't think about where the gas miners mine from. Drink your corn syrup.
/:cl:

[LORE] Updates CURRENT_STATION_YEAR

---

_maps/RandomRuins/SpaceRuins/skyrat/interdynefob.dmm

:cl:
add: DS-2's prison now has a laundry cart, meaning syndicate prisoner skirts are now, genuinely, obtainable outside of the chameleon kit. Yes, this was. Genuinely a problem.
fix: A bunch of APCs that were prior using generic access on DS-2 have been replaced with syndicate access, and the chemistry room no longer has magic power. Lol. Lmao.
/:cl:

Some Minor DS-2 Patches

---

code/world.dm

I don't beleive skyrat is liable to produce a proper fix anytime soon. This is a psuedo-permanent solution to the table/item/player layering issue.

[REQ] [Revert Later] Disables Sideplane

---

_maps/map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/IceBoxStation/IceBoxStation.dmm
_maps/map_files/KiloStation/KiloStation.dmm
_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/VoidRaptor/VoidRaptor.dmm
_maps/map_files/tramstation/tramstation.dmm
code/game/machinery/sleepers.dm
code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
code/modules/research/designs/machine_designs.dm
code/modules/research/techweb/all_nodes.dm

:cl:
add: Sleepers have been re-integrated into the techweb - with a special variant if you get illegal tech.
balance: As a consequence, illegal tech now requires advanced biotech. I hope you've been chugging your experiment juice if you want the gamer guns(tm).
balance: Lavaland podperson sleepers no longer are deconstructable.
/:cl:

[REQ] Re-Implements Sleepers

---

_maps/map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/IceBoxStation/IceBoxStation.dmm
_maps/map_files/KiloStation/KiloStation.dmm
_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/VoidRaptor/VoidRaptor.dmm
_maps/map_files/tramstation/tramstation.dmm

:cl:
balance: Medical now gets the SAD roundstart.
/:cl:

[REQ] Adds a SAD To medbay roundstart

---

code/_globalvars/lists/maintenance_loot.dm
code/modules/cargo/packs/organic.dm
code/modules/projectiles/guns/energy/pulse.dm

https://www.youtube.com/watch?v=fHH-f-IdbZM
:cl:
del: The die of fate (and it's cursed counterpart) can no longer spawn in maint.
del: Pizza bombs and infinite pizzas can no longer come from Cargo.
balance: The arcade pulse rifle now fires only practice rounds. Boowomp.
/:cl:

[REQ] Kills All Fun FOREVER (No More Fun (Lightning Crackle)

---

code/modules/mining/lavaland/tendril_loot.dm
code/modules/research/designs/misc_designs.dm
modular_skyrat/modules/cellguns/code/medigun_research.dm

still having required reagents is bad praxis, this was meant to be phased out. like two /tg/ designs still used it and we have sleepers anyways so medicells having them for free-ish isn't THAT unreasonable

[REQ] Purges Required Reagents From Protolathe Designs

---

code/__DEFINES/mobs.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/hemophage.dm

This is absolutely not the best way to go about addressing how often/much people need to eat (or slurpy, in the case of hemophages), but it's the only one I found defines for, so... oops?
also does the same for ethereals.

[REQ] Halves Hunger Rate, Matches Hemophage Bloodloss With It

---

modular_skyrat/modules/event_vote/code/event_chaos_system.dm

With shifts now being greenshifts the SR system must be changed, this disables a number of them from rolling during the admin vote in the event panel. DO NOT SPEEDMERGE, if there are event problems i need to review some test logs from an actual round as im not spending 6 hours in a round with 30 empty bots
by the grace of allah remove this anteg reee, idfk yall asked me
<details>
https://pastebin.com/EWw2SVTU (this was a log of making some low, med, and high chaos admin votes, when not voted no event will roll due to it being a greenshift)
</details>
:cl:
balance:disables 'highly destructive' and antag events
/:cl:

{Testmerge until i can review more data from an actual round} Disables some events from the chaos SR system

---

code/modules/cargo/packs/materials.dm

Adds crates for 10 sheets of uranium, gold, and silver to the cargo manifest for 3000, 4000, and 3000 respectively, sold with a total loss of 45%~ if refunded.
Easy solution to not rush BSM's and if miners are dogwater
<details>
</details>
:cl:
add: Material crates
/:cl:

Material Crates

---

.github/workflows/docker_publish.yml

elgohr/Publish-Docker-Github-Action@master is not supported anymore

Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)

---

code/modules/research/designs/machine_designs.dm
code/modules/research/designs/power_designs.dm

This has been bothering me forever, it's the one board design you can't make in a circuit imprinter (but can make anywhere else?)
This fixes that, along with moving it's material cost and buildspeed in line with the others.
Also clarifies just how much power both can generate.

[FUCK] Makes RTG Boards Designs not C+V'd power cell Designs

---

code/game/objects/items/implants/implant_compliance.dm

TL;DR - Stops you from putting your name into the compliance implant without emagging it. This is TECHNICALLY still cheesable, but the chance you can get a middleman to configure it.. at that point, it's dedication to just being a knobhead.

Guards Against Misusing The Compliance Implant

---

code/modules/research/designs/mecha_designs.dm
code/modules/research/techweb/all_nodes.dm
code/modules/vehicles/mecha/combat/gygax.dm
code/modules/vehicles/mecha/combat/honker.dm
code/modules/vehicles/mecha/combat/marauder.dm
code/modules/vehicles/mecha/equipment/tools/other_tools.dm

Debated on how to do this but ultimately decided they should be base tech.
- Separates Ion Thrusters into two types: Internal and External. Internal are the kind that comes stock on Nukie/CC Mechs, External are...
- The printable kind. Middlingly expensive, not very compared to the rest of assembling a mech.
- To slot them in effectively, advanced weapons tech now required advanced mecha tech. (This does mean that advanced weaponry is locked behind biotech, but if you aren't doing dissections, you don't deserve gamer guns methinks.)

[REQ] Ion Mecha Thrusters

---

code/modules/mob/living/carbon/emote.dm

_"I get sad, and I do a spicy *jerk"_
Implements the unused "coom" hand_item which allows the player to masturbate and "coom" into containers, on people, items and themselves with their penis.
Cum sluts can enjoy their favorite beverage in a wine glass. (mmm fancy)
A chef can make some new, salty condiments. (*chefkiss)
Overall, the fact that we can't collect coom properly normally is an unforgivable sin, which can only be absolved by merging this commit.
<details>
</details>
:cl:
add: implemented the unused masturbation hand item, activated with *jerk
/:cl:

implements the unused masturbation item as an emote, triggered by *jerk

---

code/datums/mutations/body.dm
code/modules/clothing/sizeclothing.dm
modular_skyrat/modules/emotes/code/additionalemotes/turf_emote.dm
modular_skyrat/modules/size_gear/code/size_gear.dm

Fixes the giant and dwarf mutations so they can't be exploited when used with the normalizer. Also makes it so the resizer takes it into account for size adjustment.
Also fixes the *turf emote tail sprite scaling. Scaling to character scale rather then your size in prefrences.

gigantism and dwarfism fixes.

---

modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/genitals.dm

A oversight that ment that if you had a bra of any sort, even with it hidden, it would hide all genitalia no matter where it was. Just fixes it by correcting the check.

A hotfix for underwear and bras.
