code/modules/mob/living/carbon/human/species_types/ethereal.dm
code/modules/mob/living/carbon/human/species_types/felinid.dm
code/modules/mob/living/carbon/human/species_types/flypeople.dm
code/modules/mob/living/carbon/human/species_types/golems.dm
code/modules/mob/living/carbon/human/species_types/humans.dm
code/modules/mob/living/carbon/human/species_types/jellypeople.dm
code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
code/modules/mob/living/carbon/human/species_types/monkeys.dm
code/modules/mob/living/carbon/human/species_types/mothmen.dm
code/modules/mob/living/carbon/human/species_types/plasmamen.dm
code/modules/mob/living/carbon/human/species_types/podpeople.dm
modular_skyrat/modules/better_vox/code/vox_species.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/akula.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/aquatic.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/dwarf.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/ghoul.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/humanoid.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/insect.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/lizard.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/mammal.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/placeholder_helper.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/podweak.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/robotic/synthetic.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/skrell.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/tajaran.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/unathi.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/vox.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/vulpkanin.dm
modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/xeno.dm
modular_skyrat/modules/teshari/code/_teshari.dm

No more monkey business.
</details>
:cl:
balance: All species have now are equally paid thanks to new Union contracts. Minus Monkies.
/:cl:

Buffs pay for all Species, minus humans, and nerfs monkey payday

---

code/modules/mining/machine_redemption.dm

it's no longer placebo, I've known this whole time, i just didn't say anything because i didn't want miners to bitch and stop supplying the station 💀 
:cl:
add: ORMs are now affected by stock parts again.
/:cl:

Re-Adds ORM Upgrades

---

code/modules/research/designs/biogenerator_designs.dm

Host Request
:cl:
add: Ketchup's been added to the Biogenerator.
/:cl:

Throws Ketchup in the Biogen

---

code/game/objects/items/devices/multitool.dm
code/game/objects/items/food/pizza.dm
modular_skyrat/modules/alternative_job_titles/code/alt_job_titles.dm

:cl:
del: Arnold Pizza no longer delimbs. Boowomp.
/:cl:

[REQ] PR That Was Built On An Ancient Fallout 13 Burial Ground

---

code/modules/research/designs/machine_designs.dm
code/modules/research/techweb/all_nodes.dm

:cl:
balance: Bullet Drive Boards are now printable.
/:cl:

[REQ] Bullet Drive RND

---

code/modules/hydroponics/grown/mushrooms.dm

No player-facing changes, I'm just stupid

[FUCK] Glowshroom Patch

---

code/modules/paperwork/fax.dm

[REQ] Rename Fax Departments

---

modular_skyrat/modules/verbs/code/looc.dm

Enables looc while unconscious
Allows Use of looc while passed out/etc, Useful to deal with stuff involving prefs or etc
<details>
</details>
:cl:
del: Removes the check for being passed out for looc
/:cl:

LOOC while Unconcious

---

code/modules/mining/ores_coins.dm
modular_skyrat/modules/bluespace_miner/code/bluespace_miner.dm

I panicked thinking the reason I couldn't print these while testing was because I fucked up the designs. Turns out it was just me wearing the BST ID card. Lol. Lmao
*You can now toggle between processed materials and raw materials with a screwdriver, rather than it being locked behind three identical research nodes(????)*

[REQ] Completely Redoes Raw Bluespace Miners, Nerfs Point Output

---

modular_skyrat/master_files/code/modules/client/preferences/mutant_parts.dm
modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/head_accessory.dm
modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/neck_accessory.dm

Yes this item was originally a donor item of mine, congrats its now free for all.
Already in game, changed ckeys, want access bacc but also nao everyone can use it (its also currently accessible if you're a slime through the menu cause shitcode)
<details>
</details>
:cl:
del:ckey check for neck/head_acc
/:cl:

Removes a ckey check for head/neck_acc

---

modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/hemophage.dm

Mass Hemophage Change Port.
Makes hemophages less shitty LOL
:cl:
tweak: Mass Hemophage Changes
/:cl:

Hemophage Compressed Update

---

modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/hemophage.dm

Reverts JasmineRickards/T.E.-station#41
AGPL3 'Ownership of code' reversion.
Refusal will be met with escalating consequences, but I do not want my code, my name, or otherwise my GitHub contributions to be associated with this project.

Revert "Hemophage Compressed Update"

---

code/modules/research/designs/mechfabricator_designs.dm
code/modules/research/techweb/all_nodes.dm

Adds the syndicate storage module and advanced jetpack to illegal tech.
Yeah.

[REQ] Printable Syndicate Storage + Advanced Jetpack

---

code/modules/reagents/chemistry/machinery/chem_master.dm

trim() wasn't being called properly, and a cheaty boy took note of this.

[FUCK] Fixes the Chemmaster allowing for easy HTML execution

---

modular_skyrat/modules/modular_items/lewd_items/code/lewd_arousal/climax.dm

Almost everyone hates the current climax sounds so i simply relaced it with sounds / misc / soggy.ogg
No more annoying/cring sound
<details>
</details>
:cl:
qol:Different cum sound
/:cl:

Slightly Better Cum Sounds

---

modular_skyrat/modules/bluespace_miner/code/bluespace_miner.dm

yeah this got comedically annoying comedically fast

Stops Bluespace Miners' Sounds From Piercing Walls (And Slightly Lowers The Volume)

---

_maps/RandomRuins/SpaceRuins/skyrat/luna.dmm
_maps/map_files/VoidRaptor/VoidRaptor.dmm

Fixes VoidRaptor Runtimes, Updates Luna

---

code/modules/cargo/exports/xenobio.dm
code/modules/reagents/chemistry/recipes/slime_extracts.dm
modular_skyrat/modules/aesthetics/cells/cell.dm

yeah they were using the old path because SR

[FUCK] Fixes Yellow Slime Plasma Reactions

---

_maps/map_files/PubbyStation/PubbyStation.dmm

- ARRIVALS ACTUALLY WORKS NOW SO YOU AREN'T TRAPPED ON THE INTERLINK OOPS
- The Ferry too

PUBBY PATCH LAP 2 (P-RANK)

---

_maps/map_files/PubbyStation/PubbyStation.dmm

PUBBY FIXES LAP 3 - PUBBYFACE IS AFTER ME HELP

---

_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/shuttles/escape_pod_large.dmm
code/modules/shuttle/emergency.dm
code/modules/shuttle/monastery.dm

- ARRIVALS
- CARGO WINDOORS
- AP CHAMBER
- THE ESCAPE POD

Pubby fixes LAP FOUR - aaAAAAAAAAAAAAAAA

---

code/modules/cargo/packs/security.dm

[REQ] Emag-Purchasable Syndicate Revolvers from Cargo

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Revert "Update PubbyStation.dmm"

---

code/game/objects/items/food/snacks.dm

also slightly buffs the reagents

[REQ] De-Junkfoods Homemade Sunflower Seeds

---

code/modules/atmospherics/machinery/pipes/pipes.dm

Fixes the layer manifolds missing the sprite parts.
We had used a separate function cutting all overlays, thinking it was called first before the rest, but nope, so I moved it to an overlay proc built in.
Proof:
<details>
</details>
:cl:
fix: Fixed missing pipe sprite on the layer manifolds
/:cl:

Fixes layer manifolds missing their overlays.

---

code/datums/components/riding/riding_mob.dm
code/modules/mob/living/carbon/carbon_update_icons.dm
code/modules/mob/living/living_update_icons.dm

This just changes the offset values of piggy backing, and fireman carry, so that it's determined by the sizes of the characters rather then hard set values.
Also fixes being knocked down so that it centers you instead of making you a log at your feet.

fixes laying down, fireman carry, and piggy backing.
